<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Native\libplume.dylib" Condition="'$([System.OperatingSystem]::IsMacOS())' == 'true'">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>libplume.dylib</Link>
        </Content>
    </ItemGroup>
</Project>
